version: "3"
services: 
  grist:
    image: gristlabs/grist
    container_name: grist_dwh
    restart: unless-stopped
    environment: 
      - PUID=1000
      - PGID=1000
      - DEBUG=1
      - TIMEZONE=Moscow
      - APP_HOME_URL=
      - APP_DOC_URL=
      - GRIST_SAML_SP_HOST=
      - GRIST_SAML_IDP_LOGIN=
      - GRIST_SINGLE_ORG=
      - GRIST_ORG_IN_PATH=true
      - GRIST_SAML_IDP_LOGOUT=
      - GRIST_SAML_IDP_UNENCRYPTED=1
      - GRIST_SAML_SP_CERT=
      - GRIST_SAML_SP_KEY=
      - GRIST_SAML_IDP_CERTS=
      - APP_DOC_INTERNAL_URL=
    volumes:
      - ./persist:/persist
    ports:
      - 8484:8484
    

  metabase:
    image: metabase/metabase:latest
    container_name: metabase_dwh
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: metabase_db
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      - metabase_db

  metabase_db:
    image: postgres:latest
    container_name: metabase_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./metabase_db/data:/var/lib/postgresql/data
